// <auto-generated />
using System;
using BNP.Movimentacoes.Infraestrutura.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BNP.Movimentacoes.Infraestrutura.Migrations
{
    [DbContext(typeof(MovimentacoesDbContext))]
    partial class MovimentacoesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BNP.Movimentacoes.Dominio.Entidades.MovimentoManual", b =>
                {
                    b.Property<decimal>("DatMes")
                        .HasColumnType("numeric(2, 0)")
                        .HasColumnName("DAT_MES");

                    b.Property<decimal>("DatAno")
                        .HasColumnType("numeric(4, 0)")
                        .HasColumnName("DAT_ANO");

                    b.Property<decimal>("NumLancamento")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("NUM_LANCAMENTO");

                    b.Property<string>("CodCosif")
                        .IsRequired()
                        .HasColumnType("char(11)")
                        .HasColumnName("COD_COSIF");

                    b.Property<string>("CodProduto")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .HasColumnName("COD_PRODUTO");

                    b.Property<string>("CodUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("COD_USUARIO");

                    b.Property<DateTime>("DatMovimento")
                        .HasColumnType("datetime")
                        .HasColumnName("DAT_MOVIMENTO");

                    b.Property<string>("DesDescricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DES_DESCRICAO");

                    b.Property<decimal>("ValValor")
                        .HasColumnType("numeric(18, 2)")
                        .HasColumnName("VAL_VALOR");

                    b.HasKey("DatMes", "DatAno", "NumLancamento");

                    b.HasIndex("CodProduto", "CodCosif");

                    b.ToTable("MOVIMENTO_MANUAL", (string)null);
                });

            modelBuilder.Entity("BNP.Movimentacoes.Dominio.Entidades.Produto", b =>
                {
                    b.Property<string>("CodProduto")
                        .HasColumnType("char(4)")
                        .HasColumnName("COD_PRODUTO");

                    b.Property<string>("DesProduto")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("DES_PRODUTO");

                    b.Property<string>("StaStatus")
                        .HasColumnType("char(1)")
                        .HasColumnName("STA_STATUS");

                    b.HasKey("CodProduto");

                    b.ToTable("PRODUTO", (string)null);

                    b.HasData(
                        new
                        {
                            CodProduto = "0001",
                            DesProduto = "Tesouro Selic",
                            StaStatus = "A"
                        },
                        new
                        {
                            CodProduto = "0002",
                            DesProduto = "CDB BNP",
                            StaStatus = "A"
                        },
                        new
                        {
                            CodProduto = "0003",
                            DesProduto = "LCI BNP",
                            StaStatus = "I"
                        });
                });

            modelBuilder.Entity("BNP.Movimentacoes.Dominio.Entidades.ProdutoCosif", b =>
                {
                    b.Property<string>("CodProduto")
                        .HasColumnType("char(4)")
                        .HasColumnName("COD_PRODUTO");

                    b.Property<string>("CodCosif")
                        .HasColumnType("char(11)")
                        .HasColumnName("COD_COSIF");

                    b.Property<string>("CodClassificacao")
                        .HasColumnType("char(6)")
                        .HasColumnName("COD_CLASSIFICACAO");

                    b.Property<string>("StaStatus")
                        .HasColumnType("char(1)")
                        .HasColumnName("STA_STATUS");

                    b.HasKey("CodProduto", "CodCosif");

                    b.ToTable("PRODUTO_COSIF", (string)null);

                    b.HasData(
                        new
                        {
                            CodProduto = "0001",
                            CodCosif = "11111111111",
                            CodClassificacao = "RENDA",
                            StaStatus = "A"
                        },
                        new
                        {
                            CodProduto = "0001",
                            CodCosif = "22222222222",
                            CodClassificacao = "RENDA",
                            StaStatus = "A"
                        },
                        new
                        {
                            CodProduto = "0002",
                            CodCosif = "33333333333",
                            CodClassificacao = "PRIV",
                            StaStatus = "A"
                        },
                        new
                        {
                            CodProduto = "0003",
                            CodCosif = "44444444444",
                            CodClassificacao = "PRIV",
                            StaStatus = "I"
                        });
                });

            modelBuilder.Entity("BNP.Movimentacoes.Dominio.Entidades.MovimentoManual", b =>
                {
                    b.HasOne("BNP.Movimentacoes.Dominio.Entidades.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("CodProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BNP.Movimentacoes.Dominio.Entidades.ProdutoCosif", "ProdutoCosif")
                        .WithMany()
                        .HasForeignKey("CodProduto", "CodCosif")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("ProdutoCosif");
                });

            modelBuilder.Entity("BNP.Movimentacoes.Dominio.Entidades.ProdutoCosif", b =>
                {
                    b.HasOne("BNP.Movimentacoes.Dominio.Entidades.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("CodProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
